/*

import Maybe exposing (Just, Nothing)

*/

function _Url_percentEncode(string) {
  return encodeURIComponent(string);
}

function _Url_percentDecode(string) {
  try {
    return __Maybe_Just(decodeURIComponent(string));
  } catch (error) {
    return __Maybe_Nothing;
  }
}

/* ESLINT GLOBAL VARIABLES
 *
 * Do not edit below this line as it is generated by tests/generate-globals.py
 */

/* eslint no-unused-vars: ["error", { "varsIgnorePattern": "_Url_.*" }] */

/* global __Maybe_Just, __Maybe_Nothing */
