/*

import Elm.Kernel.Utils exposing (Tuple0)

*/

function _Time_rawNow() {
  return Date.now();
}

const _Time_setInterval = (interval) => (onEffects) =>
  setInterval(() => {
    const now = _Time_rawNow();
    onEffects(now);
  }, interval - (_Time_rawNow() % interval));

const _Time_clearInterval = (key) => {
  clearInterval(key);
  return __Utils_Tuple0;
};

const _Time_getTimezoneOffset = () => new Date().getTimezoneOffset();

const _Time_getZoneName = () => Intl.DateTimeFormat().resolvedOptions().timeZone;

/* ESLINT GLOBAL VARIABLES
 *
 * Do not edit below this line as it is generated by tests/generate-globals.py
 */

/* eslint no-unused-vars: ["error", { "varsIgnorePattern": "_Time_.*" }] */

/* global __Utils_Tuple0 */
