#! /usr/bin/env python3

import subprocess
import os
import sys

res = subprocess.run(
    [os.path.join(os.path.dirname(__file__), 'another-elm-wrapper'), 'elm'] +
    sys.argv[1:])

if res.returncode != 0:
    exit(res.returncode)
