/*

import Elm.Kernel.Utils exposing (Tuple0)
import Result exposing (Err, Ok)

*/


function _Test_runThunk(thunk)
{
  try {
    // Attempt to run the thunk as normal.
    return __Result_Ok(thunk(__Utils_Tuple0));
  } catch (err) {
    // If it throws, return an error instead of crashing.
    return __Result_Err(err.toString());
  }
}

/* ESLINT GLOBAL VARIABLES
 *
 * Do not edit below this line as it is generated by tests/generate-globals.py
 */

/* eslint no-unused-vars: ["error", { "varsIgnorePattern": "_Test_.*" }] */

/* global __Utils_Tuple0 */
/* global __Result_Err, __Result_Ok */
