name: CI

on:
  push:
    branches:
      - staging
      - trying
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: python -m pip install --upgrade yapf flake8

      - uses: mpizenberg/elm-tooling-action@b6665b9d55111b51d09574b4338883ab572d100f
        with:
          cache-key: elm-home-${{ matrix.os }}
          elm: '0.19.1'
          elm-format: '0.8.5'
          elm-json: '0.2.10'

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all

      - run: ./x.py install
      - run: ./x.py check
      - run: ./x.py test
