name: CI

on:
  push:
    branches:
      - staging
      - trying
      - master

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: python -m pip install --upgrade yapf~=0.31.0 flake8~=3.9.0

      - uses: mpizenberg/elm-tooling-action@b6665b9d55111b51d09574b4338883ab572d100f
        with:
          cache-key: elm-home-${{ matrix.os }}
          elm: '0.19.1'
          elm-format: '0.8.5'
          elm-json: '0.2.10'

      - name: Create local bin dir and add it to PATH.
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install elm-test-rs
        run: |
          cd "$HOME/.local/bin"
          wget https://github.com/mpizenberg/elm-test-rs/releases/download/v1.0.0-beta/elm-test-rs_linux.tar.gz
          tar -xvf elm-test-rs_linux.tar.gz
          rm elm-test-rs_linux.tar.gz

      - run: ./x.py install
      - run: ./init.py

      - run: ./x.py check
      - run: ./x.py test
